### ISSUE TITLE
Error when starting contaniers 'exec /sbin/tini: exec format error'

### ISSUE THREAD

**Issue by aguinaldoabbj** [efrecon/docker-s3fs-client#36]
Hi,
Congrats on the initiative. However, I wasn't able to make It work. When I start the container s3fs, logs shows a 'exec /sbin/tini: exec format error'. I'm trying to run the following services:

```
version: '3.8'
services:
  s3fs:
    privileged: true
    image: efrecon/s3fs:1.91
    restart: always
    environment:
      - AWS_S3_BUCKET=media
      - AWS_S3_ACCESS_KEY_ID=xxxxxxxxxxxxxxxxxx
      - AWS_S3_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - AWS_S3_URL=xxxxxxxxxxxxxxxxxxxxxxxxxxx
    volumes:
    # This also mounts the S3 bucket to `/mnt/s3data` on the host machine
      - /media/:/opt/s3fs/bucket:rshared

  test:
    image: bash:latest
    restart: always
    depends_on:
      - s3fs
    # Just so this container won't die and you can test the bucket from within
    command: sleep infinity
    volumes:
      - /media:/data:rshared
```

What am I doing wrong?
