### ISSUE TITLE
s3fs: unable to access MOUNTPOINT error

### ISSUE THREAD

**Issue by thiagomajesk** [efrecon/docker-s3fs-client#38]
Hi! I'm having the following error trying to incorporate this image into my workflow:

```
Mounting bucket my-bucket-name onto /opt/s3fs/bucket, owner: 0:0
my-bucket-name-s3fs-1         | s3fs: unable to access MOUNTPOINT my-bucket-name: No such file or directory
```

The core idea is to have some data from Prometheus and Grafana stored into a S3 bucket.

This is a sample of my `docker-compose.yml` file:

```yaml
services:
  s3fs:
    image: efrecon/s3fs:1.91
    restart: unless-stopped
    user: root
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    devices:
      - /dev/fuse
    environment:     
      S3FS_DEBUG: 1
      S3FS_ARGS: "-o nonempty"
      AWS_S3_BUCKET: $AWS_S3_BUCKET
      AWS_S3_ACCESS_KEY_ID: $AWS_S3_ACCESS_KEY_ID
      AWS_S3_SECRET_ACCESS_KEY: $AWS_S3_SECRET_ACCESS_KEY     
    volumes:
      - ./bucket:/opt/s3fs/bucket:rshared

  prometheus:
    image: prom/prometheus:latest
    user: root
    volumes:
      - ./bucket/prometheus:/etc/prometheus
      - ./bucket/prometheus-data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --web.config.file=/etc/prometheus/web.yml
    ports:
      - 9999:9090
    depends_on: ["s3fs"]
```

It seems it can't find the directory to mount, although from what I saw in the entry point file,  the image tries to create the directory: https://github.com/efrecon/docker-s3fs-client/blob/master/docker-entrypoint.sh#L82-L85. I'm not a Docker expert, is there something else I should be doing to make this work properly?
