### ISSUE TITLE
Does anyone able to umount automcatically successfully in k8s?

### ISSUE THREAD

**Issue by grapemix** [efrecon/docker-s3fs-client#54]
I also experienced the "transport endpoint is not connected" problem for my k8s cluster and I am unable to umount my mount point from the host. However, I would like to make the recovery process automatically. Here is my trial:
```
      initContainers:
        - name: umount
          image: efrecon/s3fs:1.93
          command: ["sh", "-euxc", "! mountpoint -q \"${MY_MOUNT_PATH}\" | umount ${MY_MOUNT_PATH}"]
          securityContext:
            privileged: true
```
The idea is to umount the fs if it is being mounted before the pod get started. Unfortunately, it doesn't work. Please let us know if anyone has better idea. Thx.

ps: 
I also try thinks like the code below or its variation. All trials fail.
```
mountpoint -q \"${MY_MOUNT_PATH}\" && fusermount -u ${MY_MOUNT_PATH} || exit 0

```
